export const GET_VIDEOGAMES = 'GET_VIDEOGAMES';
export const SEARCH_NAME = 'SEARCH_NAME';
export const GET_DETAILS = 'GET_DETAILS';
export const GET_GENRES = 'GET_GENRES';
export const FILTER_CREATED = 'FILTER_CREATED';